name: Build iOS

on:
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macos-latest
    name: Build iOS
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3
          bundler-cache: true
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          cache-dependency-path: FastlaneTest/package-lock.json
      - name: Install Node Modules
        run: cd FastlaneTest && npm ci
      # - name: Install Pods
      #   run: "cd FastlaneTest/ios && pod install"
      - name: Install gems
        run: cd FastlaneTest && bundle install
      # - name: Run Build Lane
      #   run: cd FastlaneTest && bundle exec fastlane ios build
      - name: Run App Store Connect API Lane
        run: cd FastlaneTest && bundle exec fastlane ios loadAscApiKey
