name: Create Client Release Branch

on:
  workflow_dispatch:
    inputs:
      branch_name:
        type: string
        description: "The name of the release branch, if not specified will default to release-{YYYY-mm-dd}"
        required: true
      delete_existing_branch:
        type: boolean
        description: "If checked, will delete the existing branch with the provided name"
        default: false
  workflow_call:
    inputs:
      branch_name:
        type: string
      delete_existing_branch:
        type: boolean
  push:
    branches:
      - main

jobs:
  create_branch:
    runs-on: ubuntu-latest
    name: Create Release Branch
    steps:
      - name: Set PST Timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "America/Los_Angeles"

      - name: Get Branch Name Default
        id: branch_default
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Delete Existing Release Branch
        uses: dawidd6/action-delete-branch@v3
        if: "${{ inputs.delete_existing_branch }} == true"
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branches: ${{ inputs.branch_name || format('release-{0}', steps.branch_default.outputs.date) }}

      - name: Create Release Branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ inputs.branch_name || steps.branch_default.outputs.date }}
          sha: "${{ github.event.pull_request.head.sha }}"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch_name }}

      - name: Copy Production Config
        run: cat ./production-config.json > ./FastlaneTest/test-config.json

      - name: Commit Production Config Changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Updated config to use production details"
          add: "*.json"
