name: Create Client Release Branch

on:
  workflow_dispatch:
    inputs:
      branch_name:
        type: string
        description: "The name of the release branch, if not specified will default to release-{YYYY-mm-dd}"
        required: true
  workflow_call:
    inputs:
      branch_name:
        type: string

jobs:
  create_branch:
    runs-on: ubuntu-latest
    name: Create Release Branch
    steps:
      - name: Create Release Branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ inputs.branch_name }}
          sha: "${{ github.event.pull_request.head.sha }}"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch_name }}

      - name: Copy Production Config
        run: cat ./production-config.json > ./FastlaneTest/test-config.json

      - name: Commit Production Config Changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Updated config to use production details"
          add: "*.json"
