name: Create Web Release Branch

on:
  workflow_dispatch:
    inputs:
      branch_name:
        type: string
        description: "The name of the release branch, if not specified will default to release-{YYYY-mm-dd}"
        required: true

jobs:
  create_branch:
    runs-on: ubuntu-latest
    name: Create Release Branch
    steps:
      - name: Create Release Branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ inputs.branch_name }}
          sha: "${{ github.event.pull_request.head.sha }}"
